version: "3.9"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns
    ports: ["5000:5000"]
    volumes:
      - ../mlflow_tracking/mlruns:/mlruns

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_URI=models:/telecom_churn/Production
    ports: ["8000:8000"]
    depends_on: [mlflow]
