name: CD - Build, Push to ECR, Deploy to EKS

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-south-1
  ECR_REPO: churn-api
  EKS_CLUSTER: churn-cluster
  K8S_NAMESPACE: default
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GH_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} -f docker/Dockerfile .
          docker push $REGISTRY/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Set image in Deployment and apply
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          sed -e "s#IMAGE_PLACEHOLDER#${REGISTRY}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}#g" \
              -e "s#MLFLOW_URI_PLACEHOLDER#${{ secrets.MLFLOW_TRACKING_URI }}#g" \
              -e "s#MODEL_URI_PLACEHOLDER#models:/telecom_churn/Production#g" \
              k8s/deployment.yaml | kubectl apply -f -
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Rollout status
        run: kubectl rollout status deployment/churn-api --namespace ${{ env.K8S_NAMESPACE }}
